=== thomassdk/XML-EastIndiaCompany-Treaties-Agreements/xml/EastIndiaCompany.dtd
<!-- document.dtd DTD for TREATIES, AGREEMENTS, AND ENGAGEMENTS, BETWEEN THE HONORABLE EAST INDIA COMPANY -->

<!-- The root element  'source' was chosen because the book contains many widely varying types of documents  -->

<!ELEMENT source (header, index+)>
    <!ELEMENT header (headTitle, respStmt, sourceDesc)>
        <!ELEMENT headTitle (#PCDATA) >
        <!ELEMENT respStmt (principal, resp, respDate)>
            <!ELEMENT principal (#PCDATA) >
            <!ELEMENT resp (#PCDATA) >
            <!ELEMENT respDate (#PCDATA) >
        <!ELEMENT sourceDesc (biblStruct) >
            <!ELEMENT biblStruct (monogr) >
                <!ELEMENT monogr (compiler, position, sourceTitle, imprint, notes) >
                    <!ELEMENT compiler (#PCDATA) >
                    <!ELEMENT position (#PCDATA) >
                    <!ELEMENT sourceTitle (#PCDATA) >
                    <!ELEMENT imprint (pubPlace, publisher, pubDate) >
                        <!ELEMENT pubPlace (#PCDATA) >
                        <!ELEMENT publisher (#PCDATA) >
                        <!ELEMENT pubDate (#PCDATA) >
                    <!ELEMENT notes (#PCDATA) >
                    
    <!ELEMENT index (doc+) >
      <!ATTLIST index location CDATA #REQUIRED >
        <!ELEMENT doc (cd, maintext, datePlace?, signatories?, note?, memorandum?, image)>
        <!-- The attributes for the text element are included in order to preserve the texts categoristion and pagination within the source material-->
          <!ATTLIST doc docID ID #REQUIRED >
          <!ATTLIST doc doctypeID CDATA #REQUIRED>
          <!ATTLIST doc pg CDATA #REQUIRED >
          <!-- The decision to make cd a mixed data set is due to the extremly mixed content of the source description paragraphs, preferably a way to force the inclusion of certain elements would be found-->
            <!ELEMENT cd (#PCDATA|politicalEntity|person|place|date|unknown|document)*>
                <!ELEMENT document (#PCDATA) >
                <!ATTLIST document transliteration CDATA #FIXED "true" >
                <!ELEMENT politicalEntity (#PCDATA|place)* >
                    <!ATTLIST politicalEntity transliteration CDATA #FIXED "true" >
                <!ELEMENT person (#PCDATA|rank|title|name|role|politicalEntity|unknown|place)*>
                   <!-- A unique ID was given to the parent person element to allow for the extraction of their different elements as they are mentioned, eg. 1 person may have may ranks/roles  -->
                      <!ATTLIST person personID CDATA #REQUIRED >
                    <!ELEMENT rank (#PCDATA)* >
                    <!-- All alternative spellings for transliterations are kept within a single altspell attribute, each spelling is capitalised and followed by a comma and a space-->
                      <!ATTLIST rank transliteration CDATA #FIXED "true">
                      <!-- All alternative spellings for transliterations are kept within a single altspell attribute, each spelling should be capitalised and followed by a comma and a space-->
                      <!ATTLIST rank altspell CDATA #IMPLIED >
                    <!ELEMENT title (#PCDATA)* >
                      <!ATTLIST title transliteration CDATA #FIXED "true" >
                      <!ATTLIST title seal CDATA #FIXED "true" >
                    <!ELEMENT name (#PCDATA)* >
                      <!-- It was decided to keep sig = signature as an attribute of name in order to be able to group the signature within the 'person' element so that both signature and rank could be extracted-->
                      <!ATTLIST name sig CDATA #FIXED "true" >
                      <!ATTLIST name seal CDATA #FIXED "true" >
                      <!ATTLIST name transliteration CDATA #FIXED "true" >
                    <!ELEMENT role (#PCDATA|place|rank)* >
                <!ELEMENT place (#PCDATA)* >
                  <!ATTLIST place type CDATA #IMPLIED >
                  <!ATTLIST place transliteration CDATA #IMPLIED >
                  <!ATTLIST place altspell CDATA #IMPLIED >
                <!ELEMENT date (#PCDATA|weekday|day|month|year|era|calendar|unknown)* >
                <!-- The different calendars so far discovered are Hindu, Islamic and Gregorian, more may need to be added later. Gregorian was chosen as the default as it is the calendar that occurs the most throughout the book -->
                  <!ATTLIST  date calendar (hindu|islamic|gregorian) #REQUIRED>
                  <!-- The isovalue (International Organization for Standardization date format) is included in order to facilitate an indepth ability to pull out and sort by the date, not #FIXED due to the different calendars    -->
                  <!ATTLIST date isovalue CDATA #IMPLIED >
                  <!ATTLIST date ref CDATA #FIXED "true">
                    <!ELEMENT weekday (#PCDATA) >
                    <!ELEMENT day (#PCDATA) >
                    <!ELEMENT month (#PCDATA) >
                        <!ATTLIST month altspell CDATA #IMPLIED >
                        <!ATTLIST month transliteration CDATA #FIXED "true" >
                    <!ELEMENT year (#PCDATA)>
                    <!ELEMENT era (#PCDATA) >
                      <!ATTLIST era transliteration CDATA #FIXED "true" >
                    <!ELEMENT calendar (#PCDATA) >
                      <!ATTLIST calendar altspell CDATA #IMPLIED>
                      <!ATTLIST calendar transliteration CDATA #FIXED "true" >
                <!ELEMENT unknown (#PCDATA) >
                  <!ATTLIST unknown altspell CDATA #IMPLIED >
                  <!ATTLIST unknown transliteration CDATA #FIXED "true">
             <!ELEMENT maintext (contract|prose)>
                 <!ELEMENT contract (intro?, article+, confirmation?)>
                 <!-- More elements may need to be addded here in the future if they are discovered in further source encodings -->
                 <!ELEMENT intro (#PCDATA|date|politicalEntity)* >
                  <!-- The element date is defined within the cd element -->
                  <!-- The element politicalEntity is defined within the cd element -->
                 <!ELEMENT article (#PCDATA|date|politicalEntity|place|practice|object|rank|unknown|person|document)* >
                   <!ATTLIST article number CDATA #REQUIRED >
                     <!ELEMENT practice (#PCDATA) >
                       <!ATTLIST practice transliteration CDATA #FIXED "true" >
                       <!ATTLIST practice altspell CDATA #IMPLIED >
                    <!-- The element date is defined within the cd element -->
                    <!-- The element politicalEntity is defined within the cd element -->
                    <!-- The element place is defined within the cd element -->
                    <!-- The element transliteration is defined within the cd element -->
                     <!ELEMENT object (#PCDATA) >
                       <!ATTLIST object transliteration CDATA #FIXED "true" >
                       <!ATTLIST object altspell CDATA #IMPLIED >
                 <!ELEMENT confirmation (#PCDATA) >
             <!ELEMENT prose (p+) >
                 <!ELEMENT p (#PCDATA|politicalEntity|date|place|person|unknown|document|rank)* >
                     <!-- These elements date are defined above-->
             <!ELEMENT datePlace (#PCDATA|date|place)*>
             <!-- These elements date are defined above-->
             <!ELEMENT signatories (#PCDATA|person|rank|role)*>
             <!-- These elements are defined above-->
             <!ELEMENT note (#PCDATA|place|docName|unknown)*>
                 <!ELEMENT docName (#PCDATA) >
             <!ELEMENT memorandum (#PCDATA) >
             <!ELEMENT image EMPTY>
               <!ATTLIST image src CDATA #REQUIRED>

=== thomassdk/XML-EastIndiaCompany-Treaties-Agreements/xml/individualxmldocs/Purwana granted by GHOOLAM SHAH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE source SYSTEM "file://ad.ucl.ac.uk/homed/uczctsd/DesktopSettings/Desktop/XML%20East%20India%20Company/DTD/EastIndiaCompany.dtd">
<source>
    <text index="SIND" pages="678">
        <sourceDesc><doctype ID="3" system="indian">Purwana</doctype> granted by <person><name ID="1">GHOOLAM SHAH ABBASEE</name>, <role><rank>Prince</rank> of <place>Sind</place></role></person>, in favor of the <politicalEntity>Hon’ble English East India Company</politicalEntity>, dated the <date calendar="islamic"><day>18</day>th <month altspell1="muharram">Mohurrum</month></date>, or <date calendar="gregorian"><day>22</day>nd <month>September</month> <year>1758</year>, <era>A. D.</era></date></sourceDesc>
        <maintext>
            <prose>
                <p>BE IT KNOWN TO ALL COMMANDERS, OFFICERS, FARMERS, AND INHABITANTS OF DHURAT* LAREE BUNDER, AURUNGABUNDER, CAVANDREE, DARAJAH, CHAVOTRA MASSOOLLIE, NAKASS, BARBANDIE GOOL ABAJAR, GOOJAR, RAJAGUNT, JOHILDAR, SARKAR CHACHAGON, CHARCARHALAN, SARKAR NAS-SARPOOR, HALLARCANDY, SARKAR SUISTAM, COODABAGE, SARKARLORAH, &amp; c. PLACES BELONGING T0 SARKAR, That Mr. Sumption, Goomashtah or Agent, did, for and in behalf of the Governor, belonging to the Hon'ble English Company of Bombay, inform here, that on all the goods he purchases and sells for the Honorable Company, he pays no more than 1½  per cent. Customs on the market price, which I hereby conﬁrm and order, that no more than that Custom may be received of him as usual ; but on all Europe goods which shall be sent from Bombay here, and hence to Coodabage, Lorey, Mooltan, &amp;c., or any brought from thence, they are to pay on the same half of what Customs, &amp;c. charges (such as passports, convoy, lodgings, Duar Touff Cana Chowkey, &amp;c.) the Mooltanee merchants pay ; and should there be such goods as the Mooltanees never carry, and it be impossible to know the charges and Customs on them, they (the English) are to pay half of what any of the considerable merchants pay on the same, but nobody is to demand anything more, and the same Customs, &amp;c. as are above mentioned, they are to pay on Hing, Indigo, &amp;c. goods which they never bought before, and they are also to pay 1½ per cent. Custom on the saltpetre, be it bought by themselves, or by any body for them, in Sirkar's place, or anywhere else ; but no Ofﬁcers, farmers, &amp;c. are to demand any thing more from them, but let them carry on their trade unmolested ; and the above-mentioned goods nobody else shall have liberty to buy; and I further order, that should their goods not be disposed of, and they want to carry them back, no Custom shall he demanded on them, nor on any provisions (such as cattle, goats, &amp;c. provi-sions) which they may provide at Tatta and other places, to send on board their ships for their maintenance. They are also not to demand any thing for their gardens, nor in any shape molest their Gardeners’ boats, vessels, &amp;c., conveyances, or send them on any Sirkar’s business, and it is also ordered that their chests of linen may not be opened, or the least hindrance shown them, in passing and repassing, it being contrary to our rules; and in short no one must presume to make any new Custom to their prejudice, by any former Rules or rates, or in any shape put any affront on them and their people; they have also free liberty to provide any sort of grain, and sell the same, and any Europe goods, at any rate they please. The Customs on the Duppers of Ghee, Oil, &amp;c., as also on the chests and pots of goods, are to be charged conforma-ble to the weight they put on each Dupper, chest, or pot, without weighing them again. The Customs on elephants’ teeth are to be received on the amount of sale, when sold, at the same rate as was usual in the time of the Prince Mahomed Moorad, and should the (English) Governor either buy, or build a house for a factory, at Aurungabunder, or at Tatta, my said people are to give all assistance, that it may cost but a reasonable price; and he is to have all encouragement for carrying on his trade, as it will be an advantage to the Government, but no other nations that wear hats shall have permission for it ; and as it is very necessary that I should encourage and please the English, I hereby order, that an entire compliance may be shewn to this, with-out demanding any new order every year.</p>
            </prose>
        </maintext>
        <datePlace>
            <date calendar="gregorian">Dated <day>22</day>nd <month>September</month> <year>1758</year>.</date>
        </datePlace>
        <note>* NOTE-In the spelling of these words the form has been adopted which is used in the Manuscript copy of this Purwana recorded amongst the records of the Bombay Government for the years 1758-59.</note>
        <image src=""/>
    </text>
</source>

=== thomassdk/XML-EastIndiaCompany-Treaties-Agreements/xml/individualxmldocs/TAESUR21.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE source SYSTEM "file://ad.ucl.ac.uk/homed/uczctsd/DesktopSettings/Desktop/XML%20East%20India%20Company/DTD/EastIndiaCompany.dtd">
<source>
    <text index="SURAT" pages="801">
        <sourceDesc><doctype ID="1" system="British">PROCLAMATION</doctype>, BY THE <person><rank>HON’BLE</rank> <name ID="5">JONATHAN DUNCAN</name>, <role>GOVERNOR OF BOMBAY</role></person>. DATED <place type="city" lang="hindi">SURAT</place>, THE <date calendar="gregorian"><day>15</day>TH <month>MAY</month> <year>1800</year></date></sourceDesc>
        <maintext>
            <prose>
                <p>Whereas by a Treaty concluded between the <politicalEntity>Hon’ble English Company</politicalEntity> and the <person><rank lang="hindi" altspell1="nawab">Nuwab</rank> <rank lang="hindi">Meer</rank> <name ID="8" lang="hindi">Nuseer-ood-Deen Khan</name></person>, under the date the <date calendar="gregorian"><day>13</day>th <month>May</month> <year>1800</year></date>, or the <date calendar="islamic"><day>19</day>th of <month lang="arabic">Zilhuj</month> <year>1214</year> of the <era lang="arabic">Hijree</era></date>, the said <rank lang="hindi" altspell1="nawab">Nuwab</rank> has agreed that the management and collection of the Revenues of the City of <place type="city" lang="hindi" >Surat</place>, and of the Territories, Places, and other Dependencies thereof, the administration of civil and criminal justice, and generally the entire government of the said City and its Dependencies, hall be vested forever, wholly and exclusively in the <politicalEntity>Hon’ble English Company</politicalEntity>;</p>
                <p>This is therefore to give notice to all the inhabitants of the Town of <place lang="hindi" type="city">Surat</place> and its Dependencies, that the <politicalEntity>Hon’ble Company</politicalEntity>’s exclusive Government commences from this day, being <date calendar="gregorian"><weekday>Thursday</weekday>, the <day>15</day>th of <month>May</month> <year>1800</year></date>. Or the <date calendar="islamic"><day>21</day>st of <month lang="arabic">Zilhuj</month> <year>1214</year> of the <era lang="arabic">Hijree</era></date>.  All persons now in civil offices are to continue to act under the administration of the <politicalEntity>Hon’ble Company</politicalEntity> until further orders, and under their future permanency will, of course, in a great measure, depend, under the good pleasure of Government, upon their diligence in their several trusts, and their fidelity to the <politicalEntity lang="mixed">English Sirkar</politicalEntity>.</p>
                <p><person><name ID="6">Edward Galley</name>, <rank>Esquire</rank>, has been appointed <role>Collector</role> of the <nonEW lang="hindi" type="unknown">Mokat</nonEW>s and <nonEW type="unknown">Mogalee</nonEW> of the <politicalEntity lang="hindi">Purgunas</politicalEntity></person>, and <person><name ID="9">Alexander Ramsay</name>, <rank>Esquire</rank>, <role>Judge</role> and <role>Magistrate</role> of the city</person>.  The Natives in trust in these <politicalEntity>Departments</politicalEntity> are therefore respectively to continue to act in subordination to those superior <role>Officers</role>, and such appointments or regulations as may take place will be announced in a few days, it being sufficient for the present to intimate to all the Company’s New Subjects of Surat, that the motives and object of the <politicalEntity>British Government</politicalEntity> in taking on themselves the full and entire government of <place lang="hindi" type="city">Surat</place>, have been, and are, to procure thereby a just, wise, and efficient administration for the security of the lives and properties, and the promotion of the happiness of all its inhabitants, of which, with God’s blessing, the good effects may soon be rendered manifest.</p>
            </prose>
        </maintext>
        <datePlace>
            <date calendar="gregorian"><day>15</day>th <month>May</month> <year>1800</year>.</date>
            <place type="castle">Surat Castle</place>
        </datePlace>
        <image src=""/>
    </text>
</source>
